const TOGGLE_DESCRIPTIONS = 'TOGGLE_DESCRIPTIONS';
const SET_PAGE_WORKSHOPS_LIST = 'SET_PAGE_WORKSHOPS_LIST';
const FETCHING_WORKSHOPS = 'FETCHING_WORKSHOPS';
const FETCHED_WORKSHOPS = 'FETCHED_WORKSHOPS';
const ERROR_FETCHING_WORKSHOPS = 'ERROR_FETCHING_WORKSHOPS';

export {
    TOGGLE_DESCRIPTIONS,
    SET_PAGE_WORKSHOPS_LIST,
    FETCHING_WORKSHOPS,
    FETCHED_WORKSHOPS,
    ERROR_FETCHING_WORKSHOPS
}