const FETCHING_WORKSHOPS = 'FETCHING_WORKSHOPS';
const FETCHED_WORKSHOPS = 'FETCHED_WORKSHOPS';
const ERROR_FETCHING_WORKSHOPS = 'ERROR_FETCHING_WORKSHOPS';
const NEXT_PAGE = 'NEXT_PAGE';
const SEARCH_ITEMS = 'SEARCH_ITEMS';
const FETCHED_ITEMS = 'FETCHED_ITEMS';

export {
    FETCHING_WORKSHOPS,
    FETCHED_WORKSHOPS,
    ERROR_FETCHING_WORKSHOPS,
    NEXT_PAGE,
    SEARCH_ITEMS,
    FETCHED_ITEMS
};