const FETCHING_WORKSHOPS = 'FETCHING_WORKSHOPS';
const FETCHED_WORKSHOPS = 'FETCHED_WORKSHOPS';
const ERROR_FETCHING_WORKSHOPS = 'ERROR_FETCHING_WORKSHOPS';

export {
    FETCHING_WORKSHOPS,
    FETCHED_WORKSHOPS,
    ERROR_FETCHING_WORKSHOPS
};