const TOGGLE_THEME = 'TOGGLE_THEME';

const WD_LOADING = 'WD_LOADING';
const WD_LOADED = 'WD_LOADED';
const WD_ERROR_LOADING = 'WD_ERROR_LOADING';

export {
    TOGGLE_THEME,
    WD_LOADING,
    WD_LOADED,
    WD_ERROR_LOADING
};